name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: Blatoy/eslint-action@1.0.4
#  stylelint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#      - uses: RedMser/stylelint@v1.1.2
#        env:
#          INDENT_SPACES: 4
